### ISSUE TITLE
HorizontalDragGesture is raising Exception

### ISSUE THREAD

**Issue by thrushfire** [GeekyAnts/flutter-carousel#7]
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The method 'call' was called on null.
Receiver: null
Tried calling: call(1)

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SlideSwipe.build.<anonymous closure> (package:flutter_multi_carousel/src/carousel/slide_swipe.dart:39:39)
#2      _PageViewState.build.<anonymous closure> (package:flutter/src/widgets/page_view.dart:816:33)
#3      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:131:41)
#4      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:49:20)
#5      ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:33:18)
#6      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4033:39)
#7      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:65:13)
#8      DragScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:457:139)
#9      ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:756:14)
#10     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:247:9)
#11     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:85:18)
#12     ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:128:5)
#13     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:386:14)
#14     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:545:12)
#15     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:405:54)
#16     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#17     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:405:7)
#18     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:260:9)
#19     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
#20     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
#21     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#22     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
#23     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
#24     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
#25     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#26     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#27     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#28     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#32     _invoke1 (dart:ui/hooks.dart:267:10)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
(elided 3 frames from dart:async)

Handler: "onUpdate"
Recognizer:
  HorizontalDragGestureRecognizer#f5c92
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The method 'call' was called on null.
Receiver: null
Tried calling: call(1)

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SlideSwipe.build.<anonymous closure> (package:flutter_multi_carousel/src/carousel/slide_swipe.dart:39:39)
#2      _PageViewState.build.<anonymous closure> (package:flutter/src/widgets/page_view.dart:816:33)
#3      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:131:41)
#4      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:49:20)
...
Handler: "onUpdate"
Recognizer: HorizontalDragGestureRecognizer#f5c92
  start behavior: start
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by thrushfire** [comment]
I had used a GestureDetector on top, closing this. Not an issue!
